language: php

php:
  - '7.0'

env :
  global :
    - 'FTP_USER=naziljuandagaming'
    - 'FTP_PASS=nazilst12345'

script : 
  
  - "curl -T delete.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/Project_UAS/"
  - "curl -T Edit.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/Project_UAS/"
  - "curl -T tambah.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/Project_UAS/"
  - "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/Project_UAS/"
  
